### ISSUE TITLE
"oauth signature does not match" with "WP-API/OAuth1"

### ISSUE THREAD

**Issue by sftsk** [ddo/oauth-1.0a#39]
Hello,

I have already created an issue here: https://github.com/WP-API/OAuth1/issues/146

In short your library is using a different key to what the WordPress plugin is (only secret without key). Could you please have a look and see if there is anything you could fix?

Thank you for the great plugin and work,
best,

Lukas

**Comment by rmccue** [comment]
Per the OAuth specification [in §3.4.2](https://tools.ietf.org/html/rfc5849#section-3.4.2):

>     key     is set to the concatenated values of:
>
>             1.  The client shared-secret, after being encoded
>                 (Section 3.6).
>
>             2.  An "&" character (ASCII code 38), which MUST be included
>                 even when either secret is empty.
>
>             3.  The token shared-secret, after being encoded
>                 (Section 3.6).

However, it seems like [the library accounts for this](https://github.com/ddo/oauth-1.0a/blob/0dea46b79c402ba9484e1960bc39830a823c6d24/oauth-1.0a.js#L170-L172).

@sftsk do you have `last_ampersand` set to `false`? Seems like the library should work otherwise.

**Comment by sftsk** [comment]
Hello,

sorry for not getting back before. Our project was on hold.
I have managed to get it to work.

As you were pointing out your library accounts for this, all I had to do was pass in `secret` into the `token` like follows:
```
const token = {
      oauth_token: permanentAuthParams.oauth_token,
      oauth_secret: permanentAuthParams.oauth_token_secret,
      secret: permanentAuthParams.oauth_token_secret
    };
```

It was just a little confusing to use `secret` and does not seem to be documented anywhere.

Anyway, thank you and all the best,
Lukas
